
name: 'Tests setup'
description: 'runs tests setup'
inputs:
  gh-access-token:
    description: 'Github Access Token'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: actions/setup-node@v3
    with:
       node-version: "18.18.0"
  - name: Download deps cache artifacts
    uses: actions/download-artifact@v3
    with:
      name: node_modules.tar.gz
  - name: Unzip node_modules
    shell: 'bash'
    run: tar xzf node_modules.tar.gz
  - name: Download build artifacts
    uses: actions/download-artifact@v3
    with:
        name: rainbowbx-${{ github.sha }}.zip
        path: build
  - name: Setup xvfb
    shell: 'bash'
    run: |
       sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
       # start xvfb in the background
       sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
  - name: Install Anvil
    uses: foundry-rs/foundry-toolchain@v1
    with:
       version: nightly
  - uses: actions/checkout@v3
    with:
         repository: 'rainbow-me/browser-extension-env'
         token: ${{ inputs.gh-access-token }}
         path: tmp
  - name: Copy dotenv
    shell: 'bash'
    run: cat tmp/dotenv >> .env && rm -rf tmp

