version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@rainbow-me/*"
  - package-ecosystem: "npm"
    directory: "/src/design-system/docs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
