module.exports = {
  entry: [
    'src/entries/background/index.ts',
    'src/entries/popup/index.tsx',
    'src/entries/content/*.ts',
    'src/entries/inpage/*.ts',
    'src/entries/iframe/*.tsx',
    'scripts/**/*.{js,ts}',
    'e2e/**/*.test.ts',
  ],
  project: [
    'src/**/*.{ts,tsx,js,jsx}',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/*.docs.tsx',
    '!src/design-system/docs/**/*',
  ],
  ignore: [
    'dist/**',
    'build/**',
    'src/design-system/docs/**/*',
    'src/design-system/components/**/*.examples.tsx',
    'src/design-system/components/**/*.css.ts',
    'src/design-system/styles/**/*.css.ts',
    'src/design-system/styles/designTokens.ts',
    'src/core/graphql/types/**/*',
    'src/core/graphql/__generated__/**/*',
    'src/core/resources/_template/*.ts',
    'src/**/index.{ts,tsx}',
    '**/*.config.{js,ts}',
    'webpack.*.js',
    'lavamoat/**',
  ],
  ignoreDependencies: [
    'buffer',
    '@graphql-eslint/eslint-plugin',
    '@lavamoat/preinstall-always-fail',
    'chromedriver',
    'geckodriver',
    '@vanilla-extract/webpack-plugin',
    '@types/chrome',
    'dotenv-webpack',
    'eslint-plugin-import',
    'eslint-plugin-jest',
    'copy-webpack-plugin',
    'webpack-bundle-analyzer',
    '@typescript-eslint/eslint-plugin',
    '@typescript-eslint/parser',
    '@peculiar/webcrypto',
    '@foundry-rs/hardhat-anvil',
  ],
  ignoreBinaries: [
    'anvil',
    'awk',
    'lsof',
    'sed',
    'tail',
    'zip',
    'codegen',
    'export',
  ],
  webpack: {
    config: ['webpack.config.dev.js', 'webpack.config.prod.js'],
  },
  typescript: {
    config: ['tsconfig.json'],
  },
};
