import {
  arbitrumNova,
  aurora,
  auroraTestnet,
  avalanche,
  blast,
  blastSepolia,
  bob,
  boba,
  canto,
  celo,
  celoAlfajores,
  classic,
  cronos,
  degen,
  dogechain,
  fantom,
  fantomTestnet,
  filecoin,
  filecoinCalibration,
  gnosis,
  harmonyOne,
  hedera,
  hederaTestnet,
  immutableZkEvm,
  kava,
  kavaTestnet,
  klaytn,
  lightlinkPegasus,
  lightlinkPhoenix,
  linea,
  lineaSepolia,
  lyra,
  manta,
  mantaSepoliaTestnet,
  mantle,
  mantleSepoliaTestnet,
  merlin,
  metis,
  mode,
  modeTestnet,
  moonbaseAlpha,
  moonbeam,
  opBNB,
  opBNBTestnet,
  palm,
  palmTestnet,
  pgn,
  polygonZkEvm,
  polygonZkEvmCardona,
  polygonZkEvmTestnet,
  pulsechain,
  redstone,
  ronin,
  rootstock,
  rootstockTestnet,
  saigon,
  scroll,
  scrollSepolia,
  zkSync,
  zkSyncSepoliaTestnet,
} from 'viem/chains';

import { ChainId } from '../types/chains';

export const customChainIdsToAssetNames: Record<ChainId, string> = {
  [arbitrumNova.id]: 'arbitrumnova',
  [aurora.id]: 'aurora',
  [auroraTestnet.id]: 'auroratestnet',
  [avalanche.id]: 'avalanchex',
  [blast.id]: 'blast',
  [blastSepolia.id]: 'blastsepolia',
  [bob.id]: 'bob',
  [boba.id]: 'boba',
  28882: 'bobasepolia',
  223: 'bsquared',
  1123: 'bsquaredtestnet',
  [celo.id]: 'celo',
  [celoAlfajores.id]: 'celoalfajores',
  [classic.id]: 'classic',
  1116: 'core',
  1115: 'coretestnet',
  [cronos.id]: 'cronos',
  [degen.id]: 'degen',
  [dogechain.id]: 'dogechain',
  [fantom.id]: 'fantom',
  [fantomTestnet.id]: 'fantomtestnet',
  [filecoin.id]: 'filecoin',
  [filecoinCalibration.id]: 'filecoincalibration',
  32659: 'fusion',
  46688: 'fusiontestnet',
  [harmonyOne.id]: 'harmony',
  [hedera.id]: 'hedera',
  [hederaTestnet.id]: 'hederatestnet',
  [immutableZkEvm.id]: 'immutablezkevm',
  2410: 'karak',
  8054: 'karaksepolia',
  [kava.id]: 'kavaevm',
  [kavaTestnet.id]: 'kavaevmtestnet',
  [klaytn.id]: 'klaytn',
  [lightlinkPhoenix.id]: 'lightlinkphoenix',
  [lightlinkPegasus.id]: 'lightlinkpegasus',
  [linea.id]: 'linea',
  [lineaSepolia.id]: 'lineasepolia',
  [lyra.id]: 'lyra',
  [manta.id]: 'manta',
  [mantaSepoliaTestnet.id]: 'mantasepolia',
  [mantle.id]: 'mantle',
  [mantleSepoliaTestnet.id]: 'mantlesepolia',
  [merlin.id]: 'merlin',
  686868: 'merlintestnet',
  [metis.id]: 'metis',
  59902: 'metissepolia',
  [mode.id]: 'mode',
  [modeTestnet.id]: 'modetestnet',
  [moonbaseAlpha.id]: 'moonbasealpha',
  [moonbeam.id]: 'moonbeam',
  [canto.id]: 'nativecanto',
  7701: 'nativecantotestnet',
  [opBNB.id]: 'opbnb',
  [opBNBTestnet.id]: 'opbnbtestnet',
  [palm.id]: 'palm',
  [palmTestnet.id]: 'palmtestnet',
  [pgn.id]: 'pgn',
  [polygonZkEvm.id]: 'polygonzkevm',
  [polygonZkEvmCardona.id]: 'polygonzkevmcardona',
  [polygonZkEvmTestnet.id]: 'polygonzkevmtestnet',
  [pulsechain.id]: 'pulsechain',
  943: 'pulsechaintestnet',
  1380012617: 'rari',
  1918988905: 'raritestnet',
  [redstone.id]: 'redstone',
  17069: 'redstonegarnet',
  17001: 'redstoneholesky',
  [ronin.id]: 'ronin',
  [saigon.id]: 'roninsaigon',
  [rootstock.id]: 'rootstock',
  [rootstockTestnet.id]: 'rootstocktestnet',
  [scroll.id]: 'scroll',
  [scrollSepolia.id]: 'scrollsepolia',
  [gnosis.id]: 'xdai',
  810180: 'zklink',
  810181: 'zklinktestnet',
  [zkSync.id]: 'zksync',
  [zkSyncSepoliaTestnet.id]: 'zksyncsepolia',
};
