import {
  type Chain,
  apeChain as _apeChain,
  arbitrum as _arbitrum,
  arbitrumNova as _arbitrumNova,
  arbitrumSepolia as _arbitrumSepolia,
  avalanche as _avalanche,
  avalancheFuji as _avalancheFuji,
  b3 as _b3,
  base as _base,
  baseSepolia as _baseSepolia,
  blast as _blast,
  blastSepolia as _blastSepolia,
  bsc as _bsc,
  bscTestnet as _bscTestnet,
  canto as _canto,
  celo as _celo,
  curtis as _curtis,
  degen as _degen,
  fantom as _fantom,
  forma as _forma,
  gnosis as _gnosis,
  gravity as _gravity,
  holesky as _holesky,
  immutableZkEvm as _immutableZkEvm,
  linea as _linea,
  mainnet as _mainnet,
  manta as _manta,
  mode as _mode,
  moonbeam as _moonbeam,
  optimism as _optimism,
  optimismSepolia as _optimismSepolia,
  palm as _palm,
  polygon as _polygon,
  polygonAmoy as _polygonAmoy,
  polygonZkEvm as _polygonZkEvm,
  sanko as _sanko,
  scroll as _scroll,
  sei as _sei,
  sepolia as _sepolia,
  xai as _xai,
  zksync as _zksync,
  zora as _zora,
  zoraSepolia as _zoraSepolia,
} from 'viem/chains';

import buildTimeNetworks from 'static/data/networks.json';

export const chainHardhat: Chain = {
  id: 1337,
  name: 'Hardhat',
  nativeCurrency: {
    decimals: 18,
    name: 'Hardhat ETH',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: { http: ['http://127.0.0.1:8545/1'] },
  },
  testnet: true,
};

export const chainHardhatOptimism: Chain = {
  id: 1338,
  name: 'Hardhat OP',
  nativeCurrency: {
    decimals: 18,
    name: 'Hardhat OP',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: { http: ['http://127.0.0.1:8545/1'] },
  },
  testnet: true,
};

export enum ChainName {
  apechain = 'apechain',
  apechainCurtis = 'apechain-curtis',
  arbitrum = 'arbitrum',
  arbitrumNova = 'arbitrum-nova',
  arbitrumSepolia = 'arbitrum-sepolia',
  avalanche = 'avalanche',
  avalancheFuji = 'avalanche-fuji',
  b3 = 'b3',
  base = 'base',
  baseSepolia = 'base-sepolia',
  berachain = 'berachain',
  berachainbArtio = 'berachain-bartio',
  blast = 'blast',
  blastSepolia = 'blast-sepolia',
  bsc = 'bsc',
  bscTestnet = 'bsc-testnet',
  canto = 'canto',
  celo = 'celo',
  degen = 'degen',
  fantom = 'fantom',
  forma = 'forma',
  godwoken = 'godwoken',
  gnosis = 'gnosis',
  gravity = 'gravity',
  gravitySepolia = 'gravity-sepolia',
  hardhat = 'hardhat',
  hardhatOptimism = 'hardhat-optimism',
  holesky = 'holesky',
  immutableZkEvm = 'immutable-zkevm',
  ink = 'ink',
  inkSepolia = 'ink-sepolia',
  linea = 'linea',
  loot = 'loot',
  mainnet = 'mainnet',
  manta = 'manta',
  mode = 'mode',
  moonbeam = 'moonbeam',
  opbnb = 'opbnb',
  optimism = 'optimism',
  optimismSepolia = 'optimism-sepolia',
  palm = 'palm',
  polygon = 'polygon',
  polygonAmoy = 'polygon-amoy',
  polygonZkEvm = 'polygon-zkevm',
  proofOfPlayApex = 'proof-of-play',
  proofOfPlayBoss = 'proof-of-play-boss',
  rari = 'rari',
  sanko = 'sanko',
  sankoTestnet = 'sanko-testnet',
  scroll = 'scroll',
  sei = 'sei',
  sepolia = 'sepolia',
  xai = 'xai',
  zksync = 'zksync-era',
  zora = 'zora',
  zoraSepolia = 'zora-sepolia',
}

export enum ChainId {
  apechain = _apeChain.id,
  apechainCurtis = _curtis.id,
  arbitrum = _arbitrum.id,
  arbitrumNova = _arbitrumNova.id,
  arbitrumSepolia = _arbitrumSepolia.id,
  avalanche = _avalanche.id,
  avalancheFuji = _avalancheFuji.id,
  b3 = _b3.id,
  base = _base.id,
  baseSepolia = _baseSepolia.id,
  berachain = 80094,
  berachainbArtio = 80084,
  blast = _blast.id,
  blastSepolia = _blastSepolia.id,
  bsc = _bsc.id,
  bscTestnet = _bscTestnet.id,
  canto = _canto.id,
  celo = _celo.id,
  degen = _degen.id,
  fantom = _fantom.id,
  forma = _forma.id,
  gnosis = _gnosis.id,
  gravity = _gravity.id,
  gravitySepolia = 13505,
  godwoken = 71402,
  hardhat = chainHardhat.id,
  hardhatOptimism = chainHardhatOptimism.id,
  holesky = _holesky.id,
  immutableZkEvm = _immutableZkEvm.id,
  ink = 57073,
  inkSepolia = 763373,
  linea = _linea.id,
  loot = 5151706,
  mainnet = _mainnet.id,
  manta = _manta.id,
  mode = _mode.id,
  moonbeam = _moonbeam.id,
  opbnb = 204,
  optimism = _optimism.id,
  optimismSepolia = _optimismSepolia.id,
  palm = _palm.id,
  polygon = _polygon.id,
  polygonAmoy = _polygonAmoy.id,
  polygonZkEvm = _polygonZkEvm.id,
  proofOfPlayApex = 70700,
  proofOfPlayBoss = 70701,
  rari = 1380012617,
  sanko = _sanko.id,
  sankoTestnet = 1992,
  scroll = _scroll.id,
  sei = _sei.id,
  sepolia = _sepolia.id,
  xai = _xai.id,
  zksync = _zksync.id,
  zora = _zora.id,
  zoraSepolia = _zoraSepolia.id,
}

export const chainNameToIdMapping: {
  [key in ChainName | 'ethereum' | 'ethereum-sepolia']: ChainId;
} = {
  ['ethereum']: ChainId.mainnet,
  ['ethereum-sepolia']: ChainId.sepolia,
  [ChainName.apechain]: ChainId.apechain,
  [ChainName.apechainCurtis]: ChainId.apechainCurtis,
  [ChainName.arbitrum]: ChainId.arbitrum,
  [ChainName.arbitrumNova]: ChainId.arbitrumNova,
  [ChainName.arbitrumSepolia]: ChainId.arbitrumSepolia,
  [ChainName.avalanche]: ChainId.avalanche,
  [ChainName.avalancheFuji]: ChainId.avalancheFuji,
  [ChainName.b3]: ChainId.b3,
  [ChainName.base]: ChainId.base,
  [ChainName.baseSepolia]: ChainId.baseSepolia,
  [ChainName.berachain]: ChainId.berachain,
  [ChainName.berachainbArtio]: ChainId.berachainbArtio,
  [ChainName.blast]: ChainId.blast,
  [ChainName.blastSepolia]: ChainId.blastSepolia,
  [ChainName.bsc]: ChainId.bsc,
  [ChainName.bscTestnet]: ChainId.bscTestnet,
  [ChainName.canto]: ChainId.canto,
  [ChainName.celo]: ChainId.celo,
  [ChainName.degen]: ChainId.degen,
  [ChainName.fantom]: ChainId.fantom,
  [ChainName.forma]: ChainId.forma,
  [ChainName.gnosis]: ChainId.gnosis,
  [ChainName.gravity]: ChainId.gravity,
  [ChainName.gravitySepolia]: ChainId.gravitySepolia,
  [ChainName.godwoken]: ChainId.godwoken,
  [ChainName.hardhat]: ChainId.hardhat,
  [ChainName.hardhatOptimism]: ChainId.hardhatOptimism,
  [ChainName.holesky]: ChainId.holesky,
  [ChainName.immutableZkEvm]: ChainId.immutableZkEvm,
  [ChainName.ink]: ChainId.ink,
  [ChainName.inkSepolia]: ChainId.inkSepolia,
  [ChainName.linea]: ChainId.linea,
  [ChainName.loot]: ChainId.loot,
  [ChainName.mainnet]: ChainId.mainnet,
  [ChainName.manta]: ChainId.manta,
  [ChainName.mode]: ChainId.mode,
  [ChainName.moonbeam]: ChainId.moonbeam,
  [ChainName.opbnb]: ChainId.opbnb,
  [ChainName.optimism]: ChainId.optimism,
  [ChainName.optimismSepolia]: ChainId.optimismSepolia,
  [ChainName.palm]: ChainId.palm,
  [ChainName.polygon]: ChainId.polygon,
  [ChainName.polygonAmoy]: ChainId.polygonAmoy,
  [ChainName.polygonZkEvm]: ChainId.polygonZkEvm,
  [ChainName.proofOfPlayApex]: ChainId.proofOfPlayApex,
  [ChainName.proofOfPlayBoss]: ChainId.proofOfPlayBoss,
  [ChainName.rari]: ChainId.rari,
  [ChainName.sanko]: ChainId.sanko,
  [ChainName.sankoTestnet]: ChainId.sankoTestnet,
  [ChainName.scroll]: ChainId.scroll,
  [ChainName.sei]: ChainId.sei,
  [ChainName.sepolia]: ChainId.sepolia,
  [ChainName.xai]: ChainId.xai,
  [ChainName.zksync]: ChainId.zksync,
  [ChainName.zora]: ChainId.zora,
  [ChainName.zoraSepolia]: ChainId.zoraSepolia,
};

export const chainIdToNameMapping: {
  [key in ChainId]: ChainName;
} = {
  [ChainId.apechain]: ChainName.apechain,
  [ChainId.apechainCurtis]: ChainName.apechainCurtis,
  [ChainId.arbitrum]: ChainName.arbitrum,
  [ChainId.arbitrumNova]: ChainName.arbitrumNova,
  [ChainId.arbitrumSepolia]: ChainName.arbitrumSepolia,
  [ChainId.avalanche]: ChainName.avalanche,
  [ChainId.avalancheFuji]: ChainName.avalancheFuji,
  [ChainId.base]: ChainName.base,
  [ChainId.baseSepolia]: ChainName.baseSepolia,
  [ChainId.berachain]: ChainName.berachain,
  [ChainId.berachainbArtio]: ChainName.berachainbArtio,
  [ChainId.blast]: ChainName.blast,
  [ChainId.blastSepolia]: ChainName.blastSepolia,
  [ChainId.bsc]: ChainName.bsc,
  [ChainId.bscTestnet]: ChainName.bscTestnet,
  [ChainId.celo]: ChainName.celo,
  [ChainId.degen]: ChainName.degen,
  [ChainId.fantom]: ChainName.fantom,
  [ChainId.forma]: ChainName.forma,
  [ChainId.gnosis]: ChainName.gnosis,
  [ChainId.gravity]: ChainName.gravity,
  [ChainId.gravitySepolia]: ChainName.gravitySepolia,
  [ChainId.godwoken]: ChainName.godwoken,
  [ChainId.hardhat]: ChainName.hardhat,
  [ChainId.hardhatOptimism]: ChainName.hardhatOptimism,
  [ChainId.holesky]: ChainName.holesky,
  [ChainId.immutableZkEvm]: ChainName.immutableZkEvm,
  [ChainId.ink]: ChainName.ink,
  [ChainId.inkSepolia]: ChainName.inkSepolia,
  [ChainId.linea]: ChainName.linea,
  [ChainId.loot]: ChainName.loot,
  [ChainId.mainnet]: ChainName.mainnet,
  [ChainId.manta]: ChainName.manta,
  [ChainId.mode]: ChainName.mode,
  [ChainId.moonbeam]: ChainName.moonbeam,
  [ChainId.opbnb]: ChainName.opbnb,
  [ChainId.optimism]: ChainName.optimism,
  [ChainId.optimismSepolia]: ChainName.optimismSepolia,
  [ChainId.palm]: ChainName.palm,
  [ChainId.polygon]: ChainName.polygon,
  [ChainId.polygonAmoy]: ChainName.polygonAmoy,
  [ChainId.polygonZkEvm]: ChainName.polygonZkEvm,
  [ChainId.proofOfPlayApex]: ChainName.proofOfPlayApex,
  [ChainId.proofOfPlayBoss]: ChainName.proofOfPlayBoss,
  [ChainId.rari]: ChainName.rari,
  [ChainId.sanko]: ChainName.sanko,
  [ChainId.sankoTestnet]: ChainName.sankoTestnet,
  [ChainId.scroll]: ChainName.scroll,
  [ChainId.sei]: ChainName.sei,
  [ChainId.sepolia]: ChainName.sepolia,
  [ChainId.xai]: ChainName.xai,
  [ChainId.zksync]: ChainName.zksync,
  [ChainId.zora]: ChainName.zora,
  [ChainId.zoraSepolia]: ChainName.zoraSepolia,
};

export type Networks = typeof buildTimeNetworks;
export type BackendNetworks = Networks['backendNetworks'];
export type BackendNetwork = BackendNetworks['networks'][number];
export type CustomNetworks = Networks['customNetworks'];
export type CustomNetwork = CustomNetworks['customNetworks'][number];

// FIXME: Delete this eventually one privateMempoolTimeout is added to the backend
export type BackendNetworkWithPrivateMempoolTimeout = BackendNetwork & {
  privateMempoolTimeout: number;
};

/**
 * MergedChain is a type that combines a transformation of BackendNetwork -> Chain
 * with any additional user preferences for that chain.
 */
export type TransformedChain = Chain & {
  type: 'supported' | 'custom';
  order: number | undefined;
  enabled: boolean;
  activeRpcUrl: string;
  rpcs: Record<string, Chain>;
};

/**
 * We only store chain data with preferences for user-added custom networks.
 * For supported chains, we receive that info from the backend so no need to store it here.
 */
export type ChainPreferences = {
  activeRpcUrl: string;
  rpcs: Record<string, Chain>;
} & (
  | {
      type: 'supported';
    }
  | ({
      type: 'custom';
    } & Chain)
);
