name: 'test setup'
description: 'runs test setup'
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
    with:
       node-version: "16.20.0"
       cache: 'yarn'
  - name: Download deps cache artifacts
    uses: actions/download-artifact@v3
    with:
      name: node_modules.tar.gz
  - name: Unzip node_modules
    run: tar xzvf node_modules.tar.gz
  - name: Install latest chromedriver
    run: yarn upgrade chromedriver --latest --chromedriver_version=LATEST && yarn setup
  - name: Download build artifacts
    uses: actions/download-artifact@v3
    with:
        name: rainbowbx-${{ github.sha }}.zip
        path: build
  - name: Setup xvfb
    run: |
       sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
       # start xvfb in the background
       sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
  - name: Install chrome
    uses: browser-actions/setup-chrome@latest
    with:
           chrome-version: 'stable'
  - name: Install Anvil
    uses: foundry-rs/foundry-toolchain@v1
    with:
       version: nightly
  - uses: actions/checkout@v3
    with:
         repository: 'rainbow-me/browser-extension-env'
         token: ${{ secrets.DOTENV_GITHUB_ACCESS_TOKEN }}
         path: tmp
  - name: Copy dotenv
    run: cat tmp/dotenv >> .env && rm -rf tmp