name: 'Chrome tests setup'
description: 'runs Chrome tests setup'
inputs:
  gh-access-token:
    description: 'Github Access Token'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: ./.github/actions/testsSetup
    with:
      gh-access-token: ${{ inputs.gh-access-token }}
  - name: Install chrome
    shell: 'bash'
    run: |
      CHROME_VERSION=$(cat e2e/browsers.json | jq -r '.versions.chrome')
      npx @puppeteer/browsers install chrome@$CHROME_VERSION
