export const tabIndexes = {
  WALLET_HEADER_LEFT_BUTTON: 1,
  WALLET_HEADER_ACCOUNT_NAME: 2,
  WALLET_HEADER_RIGHT_BUTTON: 3,
  WALLET_HEADER_BUY_BUTTON: 4,
  WALLET_HEADER_COPY_BUTTON: 5,
  WALLET_HEADER_SWAP_BUTTON: 6,
  WALLET_HEADER_SEND_BUTTON: 7,
  WALLET_HEADER_TOKENS_TAB: 8,
  WALLET_HEADER_ACTIVITY_TAB: 9,
};
