export const zIndexes = {
  NAVBAR: 1,
  PROMPT: 2,
  BOTTOM_SHEET: 4,
  CUSTOM_GAS_SHEET: 5,
  EXPLAINER_BOTTOM_SHEET: 6,
  FULL_SCREEN_WINDOW_STROKE: 7,
  COMMAND_K: 8,
  TOAST: 9,
  ALERT: 9,
  WINDOW_STROKE: 10,
};
