name: 'Firefox tests setup'
description: 'runs Firefox tests setup'
inputs:
  gh-access-token:
    description: 'Github Access Token'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: ./.github/actions/testsSetup
    with:
      gh-access-token: ${{ inputs.gh-access-token }}
  - uses: browser-actions/setup-firefox@v1
    with:
      firefox-version: 'latest-devedition'
