name: 'Custom Firefox Developer Edition Setup'
description: 'Setup a specific version of Firefox Developer Edition for testing'
inputs:
  gh-access-token:
    description: 'GitHub Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/testsSetup
      with:
        gh-access-token: ${{ inputs.gh-access-token }}

    - name: Download and Setup Firefox Developer Edition
      shell: bash
      run: |
        FIREFOX_VERSION=$(cat e2e/browsers.json | jq -r '.linux.firefox.version')
        echo "PUPPETEER_CACHE_DIR=$HOME/.cache/puppeteer" >> $GITHUB_ENV
        npx --yes @puppeteer/browsers install firefox@devedition_$FIREFOX_VERSION
        FIREFOX_BIN=$(npx --yes @puppeteer/browsers list | grep -F "firefox@devedition_${FIREFOX_VERSION}" | head -1 | cut -d')' -f2- | sed -e 's/^[[:space:]]*//')
        mkdir -p /usr/lib/firefox
        ln -sf "$FIREFOX_BIN" /usr/lib/firefox/firefox
        /usr/lib/firefox/firefox --version
