name: 'Custom Firefox Developer Edition Setup'
description: 'Setup a specific version of Firefox Developer Edition for testing'
inputs:
  gh-access-token:
    description: 'GitHub Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/testsSetup
      with:
        gh-access-token: ${{ inputs.gh-access-token }}

    - name: Download and Setup Firefox Developer Edition
      shell: bash
      run: |
        FIREFOX_VERSION=$(cat e2e/browsers.json | jq -r '.versions.firefox')
        npx @puppeteer/browsers install firefox@devedition_$FIREFOX_VERSION
