import React from 'react';

import { createExample } from '../../docs/createDocs';
import source from '../../docs/utils/source.macro';
import { Inline } from '../Inline/Inline';
import { Stack } from '../Stack/Stack';

import { ButtonSymbol } from './ButtonSymbol';

export const basic = createExample({
  name: 'Basic',
  showThemes: true,
  Example: () =>
    source(
      <Inline space="10px" wrap={false}>
        <ButtonSymbol
          color="blue"
          height="36px"
          variant="raised"
          symbol="qrcode"
        />
        <ButtonSymbol
          color="blue"
          height="36px"
          variant="flat"
          symbol="qrcode"
        />
        <ButtonSymbol
          color="blue"
          height="36px"
          variant="tinted"
          symbol="qrcode"
        />
        <ButtonSymbol
          color="blue"
          height="36px"
          variant="stroked"
          symbol="qrcode"
        />
        <ButtonSymbol height="36px" variant="white" symbol="qrcode" />
        <ButtonSymbol
          color="blue"
          height="36px"
          variant="transparent"
          symbol="qrcode"
        />
      </Inline>,
    ),
});

export const colors = createExample({
  name: 'Colors',
  showThemes: 'toggle',
  Example: () =>
    source(
      <Stack space="20px">
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="accent"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="accent"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="accent"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="accent"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="accent"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="green"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="green"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="green"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="green"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="green"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="orange"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="orange"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="orange"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="orange"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="orange"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="pink"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="pink"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="pink"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="pink"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="pink"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="purple"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="purple"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="purple"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="purple"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="purple"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="red"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="red"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="red"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="red"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="red"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="yellow"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="yellow"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="yellow"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="yellow"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="yellow"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="fill"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="fill"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="fill"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="fillSecondary"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="fillSecondary"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="fillSecondary"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="surfacePrimaryElevated"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="surfacePrimaryElevated"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="surfacePrimaryElevated"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="surfacePrimaryElevatedSecondary"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="surfacePrimaryElevatedSecondary"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="surfacePrimaryElevatedSecondary"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="surfaceSecondaryElevated"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="surfaceSecondaryElevated"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="surfaceSecondaryElevated"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
        </Inline>
      </Stack>,
    ),
});

export const sizes = createExample({
  name: 'Sizes',
  showThemes: 'toggle',
  Example: () =>
    source(
      <Stack space="20px">
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="blue"
            height="44px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="44px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="44px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="44px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol height="44px" variant="white" symbol="qrcode" />
          <ButtonSymbol
            color="blue"
            height="44px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol height="36px" variant="white" symbol="qrcode" />
          <ButtonSymbol
            color="blue"
            height="36px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="blue"
            height="32px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="32px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="32px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="32px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol height="32px" variant="white" symbol="qrcode" />
          <ButtonSymbol
            color="blue"
            height="32px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="blue"
            height="28px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="28px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="28px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="28px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol height="28px" variant="white" symbol="qrcode" />
          <ButtonSymbol
            color="blue"
            height="28px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
        <Inline space="10px" wrap={false}>
          <ButtonSymbol
            color="blue"
            height="24px"
            variant="raised"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="24px"
            variant="flat"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="24px"
            variant="tinted"
            symbol="qrcode"
          />
          <ButtonSymbol
            color="blue"
            height="24px"
            variant="stroked"
            symbol="qrcode"
          />
          <ButtonSymbol height="24px" variant="white" symbol="qrcode" />
          <ButtonSymbol
            color="blue"
            height="24px"
            variant="transparent"
            symbol="qrcode"
          />
        </Inline>
      </Stack>,
    ),
});
