name: E2E Proxy Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  chrome-e2e-proxy-swap:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Install Chrome for Testing
        run: |
          npx @puppeteer/browsers install chrome@138
          echo "CHROMIUM_BIN=$(npx @puppeteer/browsers install chrome@138 | grep 'at' | awk '{print $3}')/chrome" >> $GITHUB_ENV
      
      - name: Install Foundry (for Anvil)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Generate CA Certificate
        run: node e2e/scripts/generate-ca-cert.js
      
      - name: Build Extension
        run: USE_PROXY_ONLY=true yarn build:webpack
        env:
          NODE_ENV: production
      
      - name: Run E2E Proxy Tests (Swap)
        id: ChromeE2EProxySwap
        continue-on-error: true
        run: |
          export BROWSER=chrome
          export OS=linux
          ./e2e/scripts/run-proxy-test.sh replay e2e/serial/swap/1_swapFlow1.test.ts
      
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: proxy-test-artifacts
          path: |
            screenshots/
            e2e/fixtures/swap-flow-1/har-logs/
            e2e/fixtures/swap-flow-1/recordings.json
      
      - name: Fail if tests failed
        if: steps.ChromeE2EProxySwap.outcome == 'failure'
        run: exit 1

  # Add this job to the existing build.yml's all-tests-passed job dependencies
  proxy-tests-success:
    runs-on: ubuntu-latest
    needs: [chrome-e2e-proxy-swap]
    steps:
      - name: All proxy tests passed
        run: echo "All proxy tests passed successfully"