name: Logger & Error Handling Checks

on:
  pull_request:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - '.eslintrc.js'

permissions:
  contents: read

jobs:
  logger-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run logger unit tests
        run: yarn vitest src/logger --run

      - name: Check for console.* usage
        run: |
          echo "Checking for direct console usage in production code..."
          ! grep -r "console\.\(log\|warn\|error\|debug\)" src/ \
            --include="*.ts" \
            --include="*.tsx" \
            --exclude-dir="logger" \
            --exclude="*.test.ts" \
            --exclude="*.spec.ts" \
            --exclude="testLogger.ts" || \
          (echo "❌ Found console.* statements. Please use logger instead." && exit 1)

      - name: Verify logger imports
        run: |
          echo "Checking logger import paths..."
          ! grep -r "from ['\"]\.\..*logger" src/ \
            --include="*.ts" \
            --include="*.tsx" || \
          (echo "❌ Found relative logger imports. Use '~/logger' instead." && exit 1)

      - name: Check RainbowError usage
        run: |
          echo "Checking for proper error handling..."
          # Check that catch blocks use logger.error
          ! grep -A 3 "catch.*{" src/ \
            --include="*.ts" \
            --include="*.tsx" | \
            grep "console\.error" || \
          (echo "❌ Found console.error in catch blocks. Use logger.error with RainbowError." && exit 1)

      - name: Run ESLint with logger rules
        run: |
          yarn lint --max-warnings=0 --rule "no-console:error"

      - name: Type check logger usage
        run: yarn typecheck